version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: database_2024
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - service-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    ports:
      - "80:80"
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  postgres-data:
